### ISSUE TITLE
Bump `bindgen` version

### ISSUE THREAD

**Issue by lerela** [alexrsagen/rs-usb-compat-01-sys#5]
Hi @alexrsagen 

This package keeps a dependency to a rather old `bindgen` version (0.58), that has a dependency to an old `nom` version (0.5.2), which triggers a deprecation warning:

```
warning: the following packages contain code that will be rejected by a future version of Rust: nom v5.1.2
```

This is low priority but if there is no impact it could be useful to release a new version with updated dependencies.

**Comment by alexrsagen** [comment]
Hi, thanks for letting me know. Will release an update with newer dependency versions.

**Comment by lerela** [comment]
Awesome, thank you! Can confirm `nom` 5.1.2 is gone and the warning as well.
